export type UserStatus = 'active' | 'inactive';

export const Actions = {
  CreateOrder: 'orders:create',
  EditOrder: 'orders:edit',
  AdjustStock: 'stock:adjust',
  MarkDebt: 'billing:mark_debt',
  ViewBill: 'billing:view',
  CloseBill: 'billing:close',
  ViewReports: 'reports:view',
  ViewFinancialReports: 'reports:financial:view',
  ViewEmployeePerformanceReports: 'reports:employee_performance:view',
  ViewVoidReports: 'reports:voids:view',
  ViewInventoryCostReports: 'reports:inventory_cost:view',
  ViewSalesHistory: 'sales_history:view',
  ViewAudit: 'audit:view',
  ManageMenu: 'menu:manage',
  ManageStaff: 'staff:manage',
  ManageSystem: 'system:manage',
  TransitionOrderStatus: 'orders:transition_status',
} as const;

export type Action = (typeof Actions)[keyof typeof Actions];

export const RolePermissions: Record<string, Action[]> = {
  superadmin: Object.values(Actions),
  cashier: [Actions.CreateOrder, Actions.EditOrder, Actions.ViewBill, Actions.MarkDebt, Actions.CloseBill, Actions.ViewSalesHistory, Actions.TransitionOrderStatus],
  waitstaff: [Actions.CreateOrder, Actions.EditOrder, Actions.ViewBill, Actions.TransitionOrderStatus],
  kitchen: [Actions.TransitionOrderStatus],
  bar: [Actions.TransitionOrderStatus],
  shift_lead: [
    Actions.CreateOrder,
    Actions.EditOrder,
    Actions.AdjustStock,
    Actions.ViewBill,
    Actions.MarkDebt,
    Actions.CloseBill,
    Actions.TransitionOrderStatus,
  ],
  inventory_clerk: [Actions.AdjustStock],
  financial_analyst: [Actions.ViewFinancialReports],
  operations_analyst: [Actions.ViewEmployeePerformanceReports],
  loss_prevention: [Actions.ViewVoidReports],
  inventory_accountant: [Actions.ViewInventoryCostReports],
  manager: [
    Actions.CreateOrder,
    Actions.EditOrder,
    Actions.AdjustStock,
    Actions.ViewBill,
    Actions.MarkDebt,
    Actions.CloseBill,
    Actions.ViewReports,
    Actions.ViewFinancialReports,
    Actions.ViewEmployeePerformanceReports,
    Actions.ViewVoidReports,
    Actions.ViewInventoryCostReports,
    Actions.ViewSalesHistory,
    Actions.ViewAudit,
    Actions.ManageMenu,
    Actions.ManageStaff,
    Actions.TransitionOrderStatus,
  ],
  admin: [
    Actions.CreateOrder,
    Actions.EditOrder,
    Actions.AdjustStock,
    Actions.ViewBill,
    Actions.MarkDebt,
    Actions.CloseBill,
    Actions.ViewReports,
    Actions.ViewFinancialReports,
    Actions.ViewEmployeePerformanceReports,
    Actions.ViewVoidReports,
    Actions.ViewInventoryCostReports,
    Actions.ViewSalesHistory,
    Actions.ViewAudit,
    Actions.ManageMenu,
    Actions.ManageStaff,
    Actions.TransitionOrderStatus,
  ],
};
